### PR TITLE
Get method for 4 or more reports [5 or more]

### PR DESCRIPTION
**Pull request by LordArjuna**

### CODE REVIEW

**Review by thuanvoit — CHANGES_REQUESTED** [review]
Ready to merge. Wait for #50

**Review by nilrelyt — APPROVED** [review]
great work

**Review by binayatimsina — APPROVED** [review]
Great work with getNotificationbyID. I am not exactly sure why there is getNotification though. But good work

**Review by doan1212 — APPROVED** [review]

**Review by thuanvoit — APPROVED** [review]
Good job!

**Pull request merged**
