### PR TITLE
List of requests, approve and reject requests, send requests to user …

### PR DESCRIPTION
**Pull request by LordArjuna**
…- All in one.

### CODE REVIEW

**Comment by thuanvoit** [comment]
> I will modify this accordingly. Since we have the community_user, we will not store user list in community and community list in user, I will add the status to community_user for every user. If it's public community, the status is automatically set to "APPROVED"

After the user get approved, we should return a list of pending user to avoid another request from front end.

**Comment by thuanvoit** [comment]
I don't see any point of keeping 2-3 list of the same thing

**Comment by thuanvoit** [comment]
READY TO MERGE @LordArjuna

**Review by thuanvoit — APPROVED** [review]

**Review by doan1212 — APPROVED** [review]
ready to merge

**Pull request merged**
