### PR TITLE
post methods to keep or delete posts

### PR DESCRIPTION
**Pull request by LordArjuna**

### CODE REVIEW

**Review by thuanvoit — CHANGES_REQUESTED** [review]
Ready to merge. Wait for #51

**Review by nilrelyt — APPROVED** [review]
nice work

**Review by nilrelyt — APPROVED** [review]
nice work

**Review by binayatimsina — APPROVED** [review]
Could have just made one method instead of delete and keep method. But good work.

**Review by doan1212 — APPROVED** [review]

**Review by thuanvoit — APPROVED** [review]
Good job!

**Pull request merged**
