### PR TITLE
Notification Methods

### PR DESCRIPTION
**Pull request by nilrelyt**

### CODE REVIEW

**Review by thuanvoit — APPROVED** [review]
Everything worked great but I made some modification like group notification methods into its own service for future. Great job!

**Review by thuanvoit — CHANGES_REQUESTED** [review]
wait to merge

**Review by LordArjuna — APPROVED** [review]
great work

**Review by doan1212 — APPROVED** [review]
Just connect with frontend, everything work fine, Good Job

**Review by thuanvoit — APPROVED** [review]
Great works!

**Pull request merged**
