### PR TITLE
taggedFixed [Only show users in community]

### PR DESCRIPTION
**Pull request by LordArjuna**

### CODE REVIEW

**Review by thuanvoit — CHANGES_REQUESTED** [review]
Ready to merge. Wait for #49

**Review by nilrelyt — APPROVED** [review]
Great! Needed that fix!

**Review by binayatimsina — APPROVED** [review]
Nice work

**Review by doan1212 — APPROVED** [review]

**Review by thuanvoit — APPROVED** [review]
Good job!

**Pull request merged**
